.TH "D:/SHARE/GenTreeBillboardTexture/3d/3d.cpp" 3 "st 8. pro 2010" "Version 0.9" "GenTreeBillboardTexture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/SHARE/GenTreeBillboardTexture/3d/3d.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'pgr.h'\fP
.br
\fC#include <glm/glm.hpp>\fP
.br
\fC#include <glm/gtc/matrix_projection.hpp>\fP
.br
\fC#include <glm/gtc/matrix_transform.hpp>\fP
.br
\fC#include <glm/gtc/type_ptr.hpp>\fP
.br
\fC#include <GL/gl.h>\fP
.br
\fC#include <GL/glu.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include '../grammar.h'\fP
.br
\fC#include '../param.h'\fP
.br
\fC#include <queue>\fP
.br

.SS "Funkce"

.in +1c
.ti -1c
.RI "void \fBnewTree\fP (int \fBdepth\fP, int \fBseed\fP)"
.br
.ti -1c
.RI "void \fBonInit\fP ()"
.br
.ti -1c
.RI "void \fBonWindowRedraw\fP ()"
.br
.ti -1c
.RI "void \fBonWindowResized\fP (int w, int h)"
.br
.ti -1c
.RI "void \fBonKeyDown\fP (SDLKey key, Uint16)"
.br
.ti -1c
.RI "void \fBonKeyUp\fP (SDLKey key, Uint16)"
.br
.ti -1c
.RI "void \fBonMouseMove\fP (unsigned, unsigned, int xrel, int yrel, Uint8 buttons)"
.br
.ti -1c
.RI "void \fBonMouseDown\fP (Uint8 button, unsigned, unsigned)"
.br
.ti -1c
.RI "void \fBonMouseUp\fP (Uint8, unsigned, unsigned)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Proměnné"

.in +1c
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "float \fBrx\fP = 0.0f"
.br
.ti -1c
.RI "float \fBry\fP = -90.0f"
.br
.ti -1c
.RI "float \fBpz\fP = 3.0f"
.br
.ti -1c
.RI "float \fBsxmin\fP = 0.0"
.br
.ti -1c
.RI "float \fBsymin\fP = 0.0"
.br
.ti -1c
.RI "float \fBszmin\fP = 0.0"
.br
.ti -1c
.RI "float \fBsxmax\fP = 0.0"
.br
.ti -1c
.RI "float \fBsymax\fP = 0.0"
.br
.ti -1c
.RI "float \fBszmax\fP = 0.0"
.br
.ti -1c
.RI "int \fBdepth\fP = 40"
.br
.ti -1c
.RI "int \fBseed\fP = 23505"
.br
.ti -1c
.RI "bool \fBisHoldKey\fP = false"
.br
.ti -1c
.RI "SDLKey \fBholdKey\fP = SDLK_ESCAPE"
.br
.ti -1c
.RI "\fBTreeNode\fP * \fBmytree\fP"
.br
.ti -1c
.RI "queue< \fBTreeNode\fP * > \fBprintNodes\fP"
.br
.in -1c
.SH "Dokumentace funkcí"
.PP 
.SS "int main (int argc, char * argv[])"
.SS "void newTree (int depth, int seed)"
.SS "void onInit ()"
.SS "void onKeyDown (SDLKey key, Uint16)"
.SS "void onKeyUp (SDLKey key, Uint16)"
.SS "void onMouseDown (Uint8 button, unsigned, unsigned)"
.SS "void onMouseMove (unsigned, unsigned, int xrel, int yrel, Uint8 buttons)"
.SS "void onMouseUp (Uint8, unsigned, unsigned)"
.SS "void onWindowRedraw ()"
.SS "void onWindowResized (int w, int h)"
.SH "Dokumentace proměnných"
.PP 
.SS "int \fBdepth\fP = 40"
.SS "int \fBheight\fP"
.SS "SDLKey \fBholdKey\fP = SDLK_ESCAPE"
.SS "bool \fBisHoldKey\fP = false"
.SS "\fBTreeNode\fP* \fBmytree\fP"
.SS "queue<\fBTreeNode\fP*> \fBprintNodes\fP"
.SS "float \fBpz\fP = 3.0f"
.SS "float \fBrx\fP = 0.0f"
.SS "float \fBry\fP = -90.0f"
.SS "int \fBseed\fP = 23505"
.SS "float \fBsxmax\fP = 0.0"
.SS "float \fBsxmin\fP = 0.0"
.SS "float \fBsymax\fP = 0.0"
.SS "float \fBsymin\fP = 0.0"
.SS "float \fBszmax\fP = 0.0"
.SS "float \fBszmin\fP = 0.0"
.SS "int \fBwidth\fP"
.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu GenTreeBillboardTexture.
