.TH "_guidialog" 3 "st 8. pro 2010" "Version 0.9" "GenTreeBillboardTexture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_guidialog \- 
.SH SYNOPSIS
.br
.PP
.SS "Veřejné atributy"

.in +1c
.ti -1c
.RI "GtkWidget * \fBwindow\fP"
.br
.ti -1c
.RI "GtkWidget * \fBgui_cancel\fP"
.br
.ti -1c
.RI "GtkWidget * \fBgui_sdldemo_surface\fP"
.br
.ti -1c
.RI "GtkWidget * \fBgui_treetype\fP"
.br
.ti -1c
.RI "GtkWidget * \fBgui_width\fP"
.br
.ti -1c
.RI "GtkWidget * \fBgui_height\fP"
.br
.ti -1c
.RI "GtkWidget * \fBgui_seed\fP"
.br
.ti -1c
.RI "GtkWidget * \fBgui_depth\fP"
.br
.ti -1c
.RI "GtkWidget * \fBgui_trunk\fP"
.br
.ti -1c
.RI "GtkWidget * \fBgui_leaf\fP"
.br
.in -1c
.SH "Detailní popis"
.PP 
Dialog widgets 
.SH "Dokumentace k datovým členům"
.PP 
.SS "GtkWidget* \fB_guidialog::gui_cancel\fP"
.SS "GtkWidget* \fB_guidialog::gui_depth\fP"
.SS "GtkWidget* \fB_guidialog::gui_height\fP"
.SS "GtkWidget* \fB_guidialog::gui_leaf\fP"
.SS "GtkWidget* \fB_guidialog::gui_sdldemo_surface\fP"
.SS "GtkWidget* \fB_guidialog::gui_seed\fP"
.SS "GtkWidget* \fB_guidialog::gui_treetype\fP"
.SS "GtkWidget* \fB_guidialog::gui_trunk\fP"
.SS "GtkWidget* \fB_guidialog::gui_width\fP"
.SS "GtkWidget* \fB_guidialog::window\fP"

.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu GenTreeBillboardTexture.
