.TH "D:/SHARE/GenTreeBillboardTexture/GenTreeBillboardTexture.h" 3 "st 8. pro 2010" "Version 0.9" "GenTreeBillboardTexture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/SHARE/GenTreeBillboardTexture/GenTreeBillboardTexture.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'param.h'\fP
.br
\fC#include 'vis.h'\fP
.br
\fC#include 'grammar.h'\fP
.br
\fC#include <SDL.h>\fP
.br

.SS "Funkce"

.in +1c
.ti -1c
.RI "void \fBGenTreeBillboardTexture\fP (SDL_Surface *data, unsigned int \fBseed\fP, unsigned int \fBdepth\fP, \fBPTreeType\fP typeTree, SDL_Color wood, SDL_Color leafs)"
.br
.in -1c
.SH "Dokumentace funkcí"
.PP 
.SS "void GenTreeBillboardTexture (SDL_Surface * data, unsigned int seed, unsigned int depth, \fBPTreeType\fP typeTree, SDL_Color wood, SDL_Color leafs)"
.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu GenTreeBillboardTexture.
