.TH "D:/SHARE/GenTreeBillboardTexture/grammar.cpp" 3 "st 8. pro 2010" "Version 0.9" "GenTreeBillboardTexture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/SHARE/GenTreeBillboardTexture/grammar.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <queue>\fP
.br
\fC#include 'grammar.h'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Funkce"

.in +1c
.ti -1c
.RI "\fBTreeNode\fP * \fBGenTreeBillboardTexture_grammar\fP (\fBPTreeType\fP \fBtreeType\fP, int \fBdepth\fP, int \fBseed\fP)"
.br
.in -1c
.SH "Dokumentace funkcí"
.PP 
.SS "\fBTreeNode\fP* GenTreeBillboardTexture_grammar (\fBPTreeType\fP, int, int)"Vstupem funkce je typ stromu, uroven generovani (detail), a nahodne cislo Funkce vraci ukazatel na vygenerovany strom z uzlu \fBTreeNode\fP 
.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu GenTreeBillboardTexture.
