.TH "GRules" 3 "st 8. pro 2010" "Version 0.9" "GenTreeBillboardTexture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GRules \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rules.h>\fP
.SS "Veřejné metody"

.in +1c
.ti -1c
.RI "\fBGRules\fP (int)"
.br
.ti -1c
.RI "int \fBGetRule\fP (\fBPTreeType\fP, \fBtreeNodeType\fP, vector< int > *)"
.br
.in -1c
.SH "Detailní popis"
.PP 
Trida starajici se o generovani gramatiky pro strom urciteho typu 
.SH "Dokumentace konstruktoru a destruktoru"
.PP 
.SS "GRules::GRules (int seed)"
.SH "Dokumentace k metodám"
.PP 
.SS "int GRules::GetRule (\fBPTreeType\fP name, \fBtreeNodeType\fP symbol, vector< int > * data)"Vstupem funkce je typ stromu, pravidlo, ktere je potreba rozgenerovat a vector integeru, do ktereho se nakopiruji vybrana rozgenerovana pravidla 

.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu GenTreeBillboardTexture.
