.TH "D:/SHARE/GenTreeBillboardTexture/rules.h" 3 "st 8. pro 2010" "Version 0.9" "GenTreeBillboardTexture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/SHARE/GenTreeBillboardTexture/rules.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <map>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br

.SS "Třídy"

.in +1c
.ti -1c
.RI "class \fBGRules\fP"
.br
.in -1c
.SS "Výčty"

.in +1c
.ti -1c
.RI "enum \fBPTreeType\fP { \fBPTREE_APPLE\fP, \fBPTREE_PICEA\fP, \fBPTREE_PALMA\fP, \fBPTREE_COUNT\fP }"
.br
.ti -1c
.RI "enum \fBtreeNodeType\fP { \fBTRUNK\fP, \fBBRANCH\fP, \fBBRANCH_UP\fP, \fBBRANCH_DOWN\fP, \fBTRUNK_BRANCHLESS\fP }"
.br
.in -1c
.SS "Proměnné"

.in +1c
.ti -1c
.RI "const char * \fBprintableRules\fP []"
.br
.in -1c
.SH "Dokumentace výčtových typů"
.PP 
.SS "enum \fBPTreeType\fP"Vyctovy typ reprezentujici dostupne modely stromu (gramatiky a parametry stromu) 
.PP
\fBHodnoty výčtu: \fP
.in +1c
.TP
\fB\fIPTREE_APPLE \fP\fP
.TP
\fB\fIPTREE_PICEA \fP\fP
.TP
\fB\fIPTREE_PALMA \fP\fP
.TP
\fB\fIPTREE_COUNT \fP\fP

.SS "enum \fBtreeNodeType\fP"Vyctovy typ reprezentujici casti stromu (gramatika pracuje prave s temito castmi) 
.PP
\fBHodnoty výčtu: \fP
.in +1c
.TP
\fB\fITRUNK \fP\fP
.TP
\fB\fIBRANCH \fP\fP
.TP
\fB\fIBRANCH_UP \fP\fP
.TP
\fB\fIBRANCH_DOWN \fP\fP
.TP
\fB\fITRUNK_BRANCHLESS \fP\fP

.SH "Dokumentace proměnných"
.PP 
.SS "const char* \fBprintableRules\fP[]"Pomocne pole obsahujici zkratky pro ladici vypis jednotlivych pravidel 
.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu GenTreeBillboardTexture.
