.TH "D:/SHARE/GenTreeBillboardTexture/rules.cpp" 3 "st 8. pro 2010" "Version 0.9" "GenTreeBillboardTexture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/SHARE/GenTreeBillboardTexture/rules.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include 'rules.h'\fP
.br
\fC#include 'param.h'\fP
.br

.SS "Proměnné"

.in +1c
.ti -1c
.RI "const char * \fBprintableRules\fP [] = {'T','B','B_U','B_D', 'T_NB' }"
.br
.in -1c
.SH "Dokumentace proměnných"
.PP 
.SS "const char* \fBprintableRules\fP[] = {'T','B','B_U','B_D', 'T_NB' }"Pomocne pole obsahujici zkratky pro ladici vypis jednotlivych pravidel 
.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu GenTreeBillboardTexture.
