.TH "sphericCoords" 3 "st 8. pro 2010" "Version 0.9" "GenTreeBillboardTexture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sphericCoords \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <param.h>\fP
.SS "Veřejné metody"

.in +1c
.ti -1c
.RI "\fBoperator std::string\fP ()"
.br
.in -1c
.SS "Veřejné atributy"

.in +1c
.ti -1c
.RI "float \fBr\fP"
.br
.ti -1c
.RI "float \fBtheta\fP"
.br
.ti -1c
.RI "float \fBphi\fP"
.br
.in -1c
.SH "Dokumentace k metodám"
.PP 
.SS "sphericCoords::operator std::string ()\fC [inline]\fP"
.SH "Dokumentace k datovým členům"
.PP 
.SS "float \fBsphericCoords::phi\fP"
.SS "float \fBsphericCoords::r\fP"
.SS "float \fBsphericCoords::theta\fP"

.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu GenTreeBillboardTexture.
