.TH "TreeNode" 3 "st 8. pro 2010" "Version 0.9" "GenTreeBillboardTexture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TreeNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <grammar.h>\fP
.SS "Veřejné metody"

.in +1c
.ti -1c
.RI "\fBTreeNode\fP ()"
.br
.ti -1c
.RI "\fBTreeNode\fP (\fBtreeNodeType\fP, \fBTreeNode\fP *)"
.br
.ti -1c
.RI "void \fBprintTree\fP ()"
.br
.ti -1c
.RI "void \fBprintTreeWithParams\fP ()"
.br
.in -1c
.SS "Statické veřejné metody"

.in +1c
.ti -1c
.RI "static void \fBprocessPrint\fP ()"
.br
.ti -1c
.RI "static void \fBprocessPrintWithParams\fP ()"
.br
.in -1c
.SS "Veřejné atributy"

.in +1c
.ti -1c
.RI "\fBtreeNodeType\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBTreeNode\fP * \fBparentNode\fP"
.br
.ti -1c
.RI "vector< \fBTreeNode\fP * > \fBchildNodes\fP"
.br
.ti -1c
.RI "\fBparamInfo\fP \fBparam\fP"
.br
.in -1c
.SS "Statické veřejné atributy"

.in +1c
.ti -1c
.RI "static queue< \fBTreeNode\fP * > \fBprintNodes\fP"
.br
.in -1c
.SH "Detailní popis"
.PP 
Trida reprezentujici uzel stromu v grafove reprezentaci 
.SH "Dokumentace konstruktoru a destruktoru"
.PP 
.SS "TreeNode::TreeNode ()"
.SS "TreeNode::TreeNode (\fBtreeNodeType\fP type, \fBTreeNode\fP * parent)"\fBTreeNode()\fP constructor
.PP
Konstruktor uzlu stromu (cely strom je slozen z techto uzlu) 
.SH "Dokumentace k metodám"
.PP 
.SS "void TreeNode::printTree ()"Pomocna funkce pro ladeni vystupu. Funkce prida aktualni strom do fronty a spusti generovani vetvi. (uspornejsi vypis) 
.SS "void TreeNode::printTreeWithParams ()"Pomocna funkce pro ladeni vystupu. Funkce prida aktualni strom do fronty a spusti generovani vetvi. (rozsireny vypis) 
.SS "void TreeNode::processPrint ()\fC [static]\fP"Volana funkci \fBprintTree()\fP. Obstarava samotny vypis vsech uzlu rozgenerovaneho strom (usporny vypis) 
.SS "void TreeNode::processPrintWithParams ()\fC [static]\fP"Volana funkci \fBprintTreeWithParams()\fP. Obstarava samotny vypis vsech uzlu rozgenerovaneho strom. (rozsireny vypis) 
.SH "Dokumentace k datovým členům"
.PP 
.SS "vector<\fBTreeNode\fP*> \fBTreeNode::childNodes\fP"
.SS "\fBparamInfo\fP \fBTreeNode::param\fP"
.SS "\fBTreeNode\fP* \fBTreeNode::parentNode\fP"
.SS "queue< \fBTreeNode\fP * > \fBTreeNode::printNodes\fP\fC [static]\fP"
.SS "\fBtreeNodeType\fP \fBTreeNode::type\fP"

.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu GenTreeBillboardTexture.
