.TH "D:/SHARE/GenTreeBillboardTexture/vis.cpp" 3 "st 8. pro 2010" "Version 0.9" "GenTreeBillboardTexture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/SHARE/GenTreeBillboardTexture/vis.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdio>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include 'vis.h'\fP
.br

.SS "Definice maker"

.in +1c
.ti -1c
.RI "#define \fBSWAP\fP(a, b)   a ^= b; b ^= a; a ^= b;"
.br
.in -1c
.SS "Funkce"

.in +1c
.ti -1c
.RI "int \fBclamp\fP (int val, int min, int max)"
.br
.ti -1c
.RI "float \fBfclamp\fP (float val, float min, float max)"
.br
.ti -1c
.RI "void \fBputpixel\fP (SDL_Surface *surface, size_t x, size_t y, SDL_Color c, unsigned int alpha=255)"
.br
.ti -1c
.RI "void \fBdrawleaf\fP (SDL_Surface *canvas, size_t x, size_t y, SDL_Color \fBcolor\fP, float size_ex)"
.br
.ti -1c
.RI "void \fBdrawbranch\fP (SDL_Surface *canvas, int x1, int y1, int x2, int y2, float thickness, SDL_Color wood, SDL_Color \fBleaf\fP, float leafinterval, float leafsize)"
.br
.ti -1c
.RI "void \fBGenTreeBillboardTexture_visualize\fP (SDL_Surface *data, \fBTreeNode\fP *tree, SDL_Color wood, SDL_Color leafs)"
.br
.in -1c
.SH "Dokumentace k definicím maker"
.PP 
.SS "#define SWAP(a, b)   a ^= b; b ^= a; a ^= b;"
.SH "Dokumentace funkcí"
.PP 
.SS "int clamp (int val, int min, int max)"
.SS "void drawbranch (SDL_Surface * canvas, int x1, int y1, int x2, int y2, float thickness, SDL_Color wood, SDL_Color leaf, float leafinterval, float leafsize)"
.SS "void drawleaf (SDL_Surface * canvas, size_t x, size_t y, SDL_Color color, float size_ex)"
.SS "float fclamp (float val, float min, float max)"
.SS "void GenTreeBillboardTexture_visualize (SDL_Surface * data, \fBTreeNode\fP * tree, SDL_Color wood, SDL_Color leafs)"
.SS "void putpixel (SDL_Surface * surface, size_t x, size_t y, SDL_Color c, unsigned int alpha = \fC255\fP)"
.SH "Autor"
.PP 
Generováno automaticky programem Doxygen ze zdrojových textů projektu GenTreeBillboardTexture.
